### ISSUE TITLE
word8-0.1.0 failed to install

### ISSUE THREAD

**Issue by agxcul** [kazu-yamamoto/word8#4]
cabal: ghc-pkg: ghc no longer supports single-file style package databases
(dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the
correct format.
cabal: Error: some packages failed to install:
word8-0.1.0 failed during the building phase. The exception was:
ExitFailure 1

hmm..it's already solved by myself..
I've updated my cabal.

**Comment by kazu-yamamoto** [comment]
Please close this issue by yourself if you resolved.
